# Generated by Django 5.0.4 on 2025-10-15 23:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/agents/')),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('PLAYERS', 'Player Representation'), ('TEAMS', 'Team Management'), ('COACHES', 'Coaching Staff'), ('RECRUITMENT', 'Recruitment'), ('GENERAL', 'General Sports Management')], default='GENERAL', max_length=20)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, help_text='Professional qualifications and certifications')),
                ('clients', models.TextField(blank=True, help_text='Notable clients or achievements')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('social_media', models.TextField(blank=True, help_text='Social media links')),
                ('services_offered', models.TextField(blank=True, help_text='Services offered to clients')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/players/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('position', models.CharField(blank=True, choices=[('LHP', 'Loosehead Prop'), ('HKR', 'Hooker'), ('THP', 'Tighthead Prop'), ('LKR', 'Lock'), ('BLF', 'Blindside Flanker'), ('OSF', 'Openside Flanker'), ('NO8', 'Number 8'), ('SCR', 'Scrum Half'), ('FLY', 'Fly Half'), ('LWC', 'Left Wing Centre'), ('ICR', 'Inside Centre'), ('OCR', 'Outside Centre'), ('RWC', 'Right Wing Centre'), ('LWG', 'Left Wing'), ('FUB', 'Fullback')], max_length=3)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(50)])),
                ('location', models.CharField(blank=True, max_length=100)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in kg', null=True)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('INJURED', 'Injured'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=15)),
                ('current_team', models.CharField(blank=True, max_length=100)),
                ('previous_teams', models.TextField(blank=True, help_text='List previous teams, one per line')),
                ('years_playing', models.PositiveIntegerField(blank=True, null=True)),
                ('caps', models.PositiveIntegerField(default=0, help_text='Number of international caps')),
                ('tries', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('penalties', models.PositiveIntegerField(default=0)),
                ('drop_goals', models.PositiveIntegerField(default=0)),
                ('awards', models.TextField(blank=True, help_text='List awards and achievements')),
                ('video_urls', models.TextField(blank=True, help_text='Video URLs, one per line')),
                ('highlights_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('social_media', models.TextField(blank=True, help_text='Social media links')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profiles/teams/')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('league', models.CharField(blank=True, choices=[('PREMIERSHIP', 'Premiership'), ('CHAMPIONSHIP', 'Championship'), ('NATIONAL_1', 'National 1'), ('NATIONAL_2', 'National 2'), ('COUNTY', 'County'), ('AMATEUR', 'Amateur'), ('INTERNATIONAL', 'International')], max_length=20)),
                ('division', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('stadium', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('social_media', models.TextField(blank=True, help_text='Social media links')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
