# Generated by Django 5.0.4 on 2025-10-16 18:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_type', models.CharField(choices=[('club', 'Club'), ('international', 'International'), ('youth', 'Youth/Development'), ('academy', 'Academy')], default='club', max_length=20)),
                ('position_played', models.CharField(blank=True, choices=[('LHP', 'Loosehead Prop'), ('HKR', 'Hooker'), ('THP', 'Tighthead Prop'), ('LKR', 'Lock'), ('BLF', 'Blindside Flanker'), ('OSF', 'Openside Flanker'), ('NO8', 'Number 8'), ('SCR', 'Scrum Half'), ('FLY', 'Fly Half'), ('LWC', 'Left Wing Centre'), ('ICR', 'Inside Centre'), ('OCR', 'Outside Centre'), ('RWC', 'Right Wing Centre'), ('LWG', 'Left Wing'), ('FUB', 'Fullback')], max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('appearances', models.PositiveIntegerField(default=0)),
                ('tries_scored', models.PositiveIntegerField(default=0)),
                ('points_scored', models.PositiveIntegerField(default=0)),
                ('contract_type', models.CharField(choices=[('professional', 'Professional'), ('semi_pro', 'Semi-Professional'), ('amateur', 'Amateur'), ('loan', 'Loan'), ('trial', 'Trial')], default='professional', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_history', to='profiles.playerprofile')),
            ],
            options={
                'verbose_name_plural': 'Player Histories',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_rating', models.PositiveIntegerField(default=0, help_text='Speed rating (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('strength_rating', models.PositiveIntegerField(default=0, help_text='Strength rating (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('agility_rating', models.PositiveIntegerField(default=0, help_text='Agility rating (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('endurance_rating', models.PositiveIntegerField(default=0, help_text='Endurance rating (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passing_accuracy', models.PositiveIntegerField(default=0, help_text='Passing accuracy percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kicking_accuracy', models.PositiveIntegerField(default=0, help_text='Kicking accuracy percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tackling_success', models.PositiveIntegerField(default=0, help_text='Tackling success percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_matches', models.PositiveIntegerField(default=0)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('total_tries', models.PositiveIntegerField(default=0)),
                ('total_assists', models.PositiveIntegerField(default=0)),
                ('total_tackles', models.PositiveIntegerField(default=0)),
                ('total_turnovers', models.PositiveIntegerField(default=0)),
                ('major_injuries', models.TextField(blank=True, help_text='List of major injuries')),
                ('current_injuries', models.TextField(blank=True, help_text='Current injury status')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_stats', to='profiles.playerprofile')),
            ],
        ),
    ]
