from django import template

register = template.Library()

# Translation dictionaries
TRANSLATIONS = {
    'en': {
        'Home': 'Home',
        'Opportunities': 'Opportunities',
        'Network': 'Network',
        'Messages': 'Messages',
        'Login': 'Login',
        'Sign Up': 'Sign Up',
        'Connect with the Rugby Community': 'Connect with the Rugby Community',
        'Join as Player': 'Join as Player',
        'Join as Team': 'Join as Team',
        'Join as Agent': 'Join as Agent',
        'Player Profiles': 'Player Profiles',
        'Contract Opportunities': 'Contract Opportunities',
        'Professional Network': 'Professional Network',
        'Ready to Join the Rugby Community?': 'Ready to Join the Rugby Community?',
        'Create your free account today and start building your rugby career network.': 'Create your free account today and start building your rugby career network.',
        'Get Started Now': 'Get Started Now',
        'Search players, teams...': 'Search players, teams...',
        'Search': 'Search',
        'Search Results': 'Search Results',
        'Search Results for': 'Search Results for',
        'How RugbyLink Works': 'How RugbyLink Works',
        'Create Your Profile': 'Create Your Profile',
        'Set up your detailed profile with stats, videos, and career information.': 'Set up your detailed profile with stats, videos, and career information.',
        'Build Your Network': 'Build Your Network',
        'Connect with players, teams, and agents to expand your professional network.': 'Connect with players, teams, and agents to expand your professional network.',
        'Find Opportunities': 'Find Opportunities',
        'Browse and apply for contract opportunities that match your skills and goals.': 'Browse and apply for contract opportunities that match your skills and goals.',
        'Advance Your Career': 'Advance Your Career',
        'Use our platform to showcase your talent and take the next step in your rugby career.': 'Use our platform to showcase your talent and take the next step in your rugby career.',
        'Active Players': 'Active Players',
        'Professional Teams': 'Professional Teams',
        'Contract Opportunities': 'Contract Opportunities',
        'Agents & Scouts': 'Agents & Scouts',
        'The professional network for rugby players, teams, and agents worldwide.': 'The professional network for rugby players, teams, and agents worldwide.',
        'RugbyLink is the premier platform connecting rugby players, teams, and agents. Find opportunities, build your network, and advance your rugby career.': 'RugbyLink is the premier platform connecting rugby players, teams, and agents. Find opportunities, build your network, and advance your rugby career.',
        'Create detailed profiles showcasing your skills, stats, and achievements. Upload videos and connect with teams looking for talent.': 'Create detailed profiles showcasing your skills, stats, and achievements. Upload videos and connect with teams looking for talent.',
        'Discover contract opportunities from professional teams. Apply directly and track your applications through our platform.': 'Discover contract opportunities from professional teams. Apply directly and track your applications through our platform.',
        'Build your professional network by connecting with other players, teams, agents, and scouts in the rugby community.': 'Build your professional network by connecting with other players, teams, agents, and scouts in the rugby community.',
    },
    'es': {
        'Home': 'Inicio',
        'Opportunities': 'Oportunidades',
        'Network': 'Red',
        'Messages': 'Mensajes',
        'Login': 'Iniciar Sesión',
        'Sign Up': 'Registrarse',
        'Connect with the Rugby Community': 'Conecta con la Comunidad del Rugby',
        'Join as Player': 'Únete como Jugador',
        'Join as Team': 'Únete como Equipo',
        'Join as Agent': 'Únete como Agente',
        'Player Profiles': 'Perfiles de Jugadores',
        'Contract Opportunities': 'Oportunidades de Contrato',
        'Professional Network': 'Red Profesional',
        'Ready to Join the Rugby Community?': '¿Listo para Unirte a la Comunidad del Rugby?',
        'Create your free account today and start building your rugby career network.': 'Crea tu cuenta gratuita hoy y comienza a construir tu red profesional de rugby.',
        'Get Started Now': 'Comenzar Ahora',
        'Search players, teams...': 'Buscar jugadores, equipos...',
        'Search': 'Buscar',
        'Search Results': 'Resultados de Búsqueda',
        'Search Results for': 'Resultados de Búsqueda para',
        'How RugbyLink Works': 'Cómo Funciona RugbyLink',
        'Create Your Profile': 'Crea Tu Perfil',
        'Set up your detailed profile with stats, videos, and career information.': 'Configura tu perfil detallado con estadísticas, videos e información profesional.',
        'Build Your Network': 'Construye Tu Red',
        'Connect with players, teams, and agents to expand your professional network.': 'Conecta con jugadores, equipos y agentes para expandir tu red profesional.',
        'Find Opportunities': 'Encuentra Oportunidades',
        'Browse and apply for contract opportunities that match your skills and goals.': 'Navega y aplica a oportunidades de contrato que coincidan con tus habilidades y objetivos.',
        'Advance Your Career': 'Avanza Tu Carrera',
        'Use our platform to showcase your talent and take the next step in your rugby career.': 'Usa nuestra plataforma para mostrar tu talento y dar el siguiente paso en tu carrera de rugby.',
        'Active Players': 'Jugadores Activos',
        'Professional Teams': 'Equipos Profesionales',
        'Contract Opportunities': 'Oportunidades de Contrato',
        'Agents & Scouts': 'Agentes y Ojeadores',
        'The professional network for rugby players, teams, and agents worldwide.': 'La red profesional para jugadores de rugby, equipos y agentes en todo el mundo.',
        'RugbyLink is the premier platform connecting rugby players, teams, and agents. Find opportunities, build your network, and advance your rugby career.': 'RugbyLink es la plataforma líder que conecta jugadores de rugby, equipos y agentes. Encuentra oportunidades, construye tu red y avanza en tu carrera de rugby.',
        'Create detailed profiles showcasing your skills, stats, and achievements. Upload videos and connect with teams looking for talent.': 'Crea perfiles detallados que muestren tus habilidades, estadísticas y logros. Sube videos y conéctate con equipos que buscan talento.',
        'Discover contract opportunities from professional teams. Apply directly and track your applications through our platform.': 'Descubre oportunidades de contrato de equipos profesionales. Aplica directamente y rastrea tus aplicaciones a través de nuestra plataforma.',
        'Build your professional network by connecting with other players, teams, agents, and scouts in the rugby community.': 'Construye tu red profesional conectándote con otros jugadores, equipos, agentes y ojeadores en la comunidad del rugby.',
    },
    'fr': {
        'Home': 'Accueil',
        'Opportunities': 'Opportunités',
        'Network': 'Réseau',
        'Messages': 'Messages',
        'Login': 'Connexion',
        'Sign Up': 'S\'inscrire',
        'Connect with the Rugby Community': 'Connectez-vous avec la Communauté du Rugby',
        'Join as Player': 'Rejoindre en tant que Joueur',
        'Join as Team': 'Rejoindre en tant qu\'Équipe',
        'Join as Agent': 'Rejoindre en tant qu\'Agent',
        'Player Profiles': 'Profils de Joueurs',
        'Contract Opportunities': 'Opportunités de Contrat',
        'Professional Network': 'Réseau Professionnel',
        'Ready to Join the Rugby Community?': 'Prêt à Rejoindre la Communauté du Rugby?',
        'Create your free account today and start building your rugby career network.': 'Créez votre compte gratuit aujourd\'hui et commencez à construire votre réseau professionnel de rugby.',
        'Get Started Now': 'Commencer Maintenant',
        'Search players, teams...': 'Rechercher des joueurs, équipes...',
        'Search': 'Rechercher',
        'Search Results': 'Résultats de Recherche',
        'Search Results for': 'Résultats de Recherche pour',
        'How RugbyLink Works': 'Comment RugbyLink Fonctionne',
        'Create Your Profile': 'Créez Votre Profil',
        'Set up your detailed profile with stats, videos, and career information.': 'Configurez votre profil détaillé avec statistiques, vidéos et informations de carrière.',
        'Build Your Network': 'Construisez Votre Réseau',
        'Connect with players, teams, and agents to expand your professional network.': 'Connectez-vous avec des joueurs, équipes et agents pour étendre votre réseau professionnel.',
        'Find Opportunities': 'Trouvez des Opportunités',
        'Browse and apply for contract opportunities that match your skills and goals.': 'Parcourez et postulez pour des opportunités de contrat qui correspondent à vos compétences et objectifs.',
        'Advance Your Career': 'Faites Progresser Votre Carrière',
        'Use our platform to showcase your talent and take the next step in your rugby career.': 'Utilisez notre plateforme pour mettre en valeur votre talent et franchir l\'étape suivante de votre carrière de rugby.',
        'Active Players': 'Joueurs Actifs',
        'Professional Teams': 'Équipes Professionnelles',
        'Contract Opportunities': 'Opportunités de Contrat',
        'Agents & Scouts': 'Agents et Recruteurs',
        'The professional network for rugby players, teams, and agents worldwide.': 'Le réseau professionnel pour les joueurs de rugby, équipes et agents dans le monde entier.',
        'RugbyLink is the premier platform connecting rugby players, teams, and agents. Find opportunities, build your network, and advance your rugby career.': 'RugbyLink est la plateforme de référence qui connecte les joueurs de rugby, équipes et agents. Trouvez des opportunités, construisez votre réseau et faites progresser votre carrière de rugby.',
        'Create detailed profiles showcasing your skills, stats, and achievements. Upload videos and connect with teams looking for talent.': 'Créez des profils détaillés mettant en valeur vos compétences, statistiques et réalisations. Téléchargez des vidéos et connectez-vous avec des équipes à la recherche de talent.',
        'Discover contract opportunities from professional teams. Apply directly and track your applications through our platform.': 'Découvrez les opportunités de contrat des équipes professionnelles. Postulez directement et suivez vos candidatures via notre plateforme.',
        'Build your professional network by connecting with other players, teams, agents, and scouts in the rugby community.': 'Construisez votre réseau professionnel en vous connectant avec d\'autres joueurs, équipes, agents et recruteurs dans la communauté du rugby.',
    },
    'it': {
        'Home': 'Home',
        'Opportunities': 'Opportunità',
        'Network': 'Rete',
        'Messages': 'Messaggi',
        'Login': 'Accedi',
        'Sign Up': 'Registrati',
        'Connect with the Rugby Community': 'Connettiti con la Comunità del Rugby',
        'Join as Player': 'Unisciti come Giocatore',
        'Join as Team': 'Unisciti come Squadra',
        'Join as Agent': 'Unisciti come Agente',
        'Player Profiles': 'Profili dei Giocatori',
        'Contract Opportunities': 'Opportunità di Contratto',
        'Professional Network': 'Rete Professionale',
        'Ready to Join the Rugby Community?': 'Pronto a Unirti alla Comunità del Rugby?',
        'Create your free account today and start building your rugby career network.': 'Crea il tuo account gratuito oggi e inizia a costruire la tua rete professionale di rugby.',
        'Get Started Now': 'Inizia Ora',
        'Search players, teams...': 'Cerca giocatori, squadre...',
        'Search': 'Cerca',
        'Search Results': 'Risultati di Ricerca',
        'Search Results for': 'Risultati di Ricerca per',
        'How RugbyLink Works': 'Come Funziona RugbyLink',
        'Create Your Profile': 'Crea Il Tuo Profilo',
        'Set up your detailed profile with stats, videos, and career information.': 'Configura il tuo profilo dettagliato con statistiche, video e informazioni di carriera.',
        'Build Your Network': 'Costruisci La Tua Rete',
        'Connect with players, teams, and agents to expand your professional network.': 'Connettiti con giocatori, squadre e agenti per espandere la tua rete professionale.',
        'Find Opportunities': 'Trova Opportunità',
        'Browse and apply for contract opportunities that match your skills and goals.': 'Sfoglia e candidati per opportunità di contratto che corrispondono alle tue abilità e obiettivi.',
        'Advance Your Career': 'Fai Avanzare La Tua Carriera',
        'Use our platform to showcase your talent and take the next step in your rugby career.': 'Usa la nostra piattaforma per mostrare il tuo talento e fare il prossimo passo nella tua carriera di rugby.',
        'Active Players': 'Giocatori Attivi',
        'Professional Teams': 'Squadre Professionali',
        'Contract Opportunities': 'Opportunità di Contratto',
        'Agents & Scouts': 'Agenti e Osservatori',
        'The professional network for rugby players, teams, and agents worldwide.': 'La rete professionale per giocatori di rugby, squadre e agenti in tutto il mondo.',
        'RugbyLink is the premier platform connecting rugby players, teams, and agents. Find opportunities, build your network, and advance your rugby career.': 'RugbyLink è la piattaforma leader che connette giocatori di rugby, squadre e agenti. Trova opportunità, costruisci la tua rete e fai avanzare la tua carriera di rugby.',
        'Create detailed profiles showcasing your skills, stats, and achievements. Upload videos and connect with teams looking for talent.': 'Crea profili dettagliati che mostrano le tue abilità, statistiche e risultati. Carica video e connettiti con squadre alla ricerca di talenti.',
        'Discover contract opportunities from professional teams. Apply directly and track your applications through our platform.': 'Scopri opportunità di contratto da squadre professionali. Candidati direttamente e traccia le tue candidature attraverso la nostra piattaforma.',
        'Build your professional network by connecting with other players, teams, agents, and scouts in the rugby community.': 'Costruisci la tua rete professionale connettendoti con altri giocatori, squadre, agenti e osservatori nella comunità del rugby.',
    },
    'pt': {
        'Home': 'Início',
        'Opportunities': 'Oportunidades',
        'Network': 'Rede',
        'Messages': 'Mensagens',
        'Login': 'Entrar',
        'Sign Up': 'Cadastrar',
        'Connect with the Rugby Community': 'Conecte-se com a Comunidade do Rugby',
        'Join as Player': 'Junte-se como Jogador',
        'Join as Team': 'Junte-se como Time',
        'Join as Agent': 'Junte-se como Agente',
        'Player Profiles': 'Perfis de Jogadores',
        'Contract Opportunities': 'Oportunidades de Contrato',
        'Professional Network': 'Rede Profissional',
        'Ready to Join the Rugby Community?': 'Pronto para se Juntar à Comunidade do Rugby?',
        'Create your free account today and start building your rugby career network.': 'Crie sua conta gratuita hoje e comece a construir sua rede profissional de rugby.',
        'Get Started Now': 'Começar Agora',
        'Search players, teams...': 'Pesquisar jogadores, times...',
        'Search': 'Pesquisar',
        'Search Results': 'Resultados da Pesquisa',
        'Search Results for': 'Resultados da Pesquisa para',
        'How RugbyLink Works': 'Como o RugbyLink Funciona',
        'Create Your Profile': 'Crie Seu Perfil',
        'Set up your detailed profile with stats, videos, and career information.': 'Configure seu perfil detalhado com estatísticas, vídeos e informações de carreira.',
        'Build Your Network': 'Construa Sua Rede',
        'Connect with players, teams, and agents to expand your professional network.': 'Conecte-se com jogadores, times e agentes para expandir sua rede profissional.',
        'Find Opportunities': 'Encontre Oportunidades',
        'Browse and apply for contract opportunities that match your skills and goals.': 'Navegue e candidate-se a oportunidades de contrato que correspondam às suas habilidades e objetivos.',
        'Advance Your Career': 'Avançar Sua Carreira',
        'Use our platform to showcase your talent and take the next step in your rugby career.': 'Use nossa plataforma para mostrar seu talento e dar o próximo passo em sua carreira de rugby.',
        'Active Players': 'Jogadores Ativos',
        'Professional Teams': 'Times Profissionais',
        'Contract Opportunities': 'Oportunidades de Contrato',
        'Agents & Scouts': 'Agentes e Olheiros',
        'The professional network for rugby players, teams, and agents worldwide.': 'A rede profissional para jogadores de rugby, times e agentes em todo o mundo.',
        'RugbyLink is the premier platform connecting rugby players, teams, and agents. Find opportunities, build your network, and advance your rugby career.': 'RugbyLink é a plataforma líder que conecta jogadores de rugby, times e agentes. Encontre oportunidades, construa sua rede e avance sua carreira de rugby.',
        'Create detailed profiles showcasing your skills, stats, and achievements. Upload videos and connect with teams looking for talent.': 'Crie perfis detalhados mostrando suas habilidades, estatísticas e conquistas. Carregue vídeos e conecte-se com times procurando talentos.',
        'Discover contract opportunities from professional teams. Apply directly and track your applications through our platform.': 'Descubra oportunidades de contrato de times profissionais. Candidate-se diretamente e acompanhe suas candidaturas através de nossa plataforma.',
        'Build your professional network by connecting with other players, teams, agents, and scouts in the rugby community.': 'Construa sua rede profissional conectando-se com outros jogadores, times, agentes e olheiros na comunidade do rugby.',
    }
}


@register.simple_tag
def trans(text, language=None):
    """Simple translation tag"""
    if not language:
        # Try to get language from context (this is a simplified approach)
        return text  # Fallback to original text
    
    translations = TRANSLATIONS.get(language, TRANSLATIONS['en'])
    return translations.get(text, text)


@register.simple_tag
def get_translation(text, language='en'):
    """Get translation for specific language"""
    translations = TRANSLATIONS.get(language, TRANSLATIONS['en'])
    return translations.get(text, text)
