# Generated by Django 5.0.4 on 2025-10-15 23:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('position', models.CharField(help_text='Rugby position (e.g., Fly Half, Prop, etc.)', max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('contract_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('SEASONAL', 'Seasonal'), ('TRIAL', 'Trial'), ('ACADEMY', 'Academy'), ('SENIOR', 'Senior'), ('JUNIOR', 'Junior')], max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=100)),
                ('requirements', models.TextField(help_text='Required skills, experience, and qualifications', max_length=1000)),
                ('benefits', models.TextField(blank=True, help_text='Additional benefits and perks', max_length=1000)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('PAUSED', 'Paused'), ('FILLED', 'Filled')], default='ACTIVE', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(limit_choices_to={'user_type': 'TEAM'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contract Opportunities',
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(help_text="Tell us why you're interested in this opportunity", max_length=2000)),
                ('cv_document', models.FileField(blank=True, null=True, upload_to='applications/cvs/')),
                ('additional_info', models.TextField(blank=True, help_text="Any additional information you'd like to share", max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWED', 'Interviewed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=15)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('team_notes', models.TextField(blank=True, help_text='Internal notes for the team', max_length=1000)),
                ('applicant', models.ForeignKey(limit_choices_to={'user_type': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.contractopportunity')),
            ],
            options={
                'ordering': ['-applied_date'],
                'unique_together': {('opportunity', 'applicant')},
            },
        ),
    ]
