# Generated by Django 5.0.4 on 2026-01-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("ARCHERY", "Archery"),
                            ("ATHLETICS", "Athletics"),
                            ("BADMINTON", "Badminton"),
                            ("BASEBALL", "Baseball"),
                            ("BASKETBALL", "Basketball"),
                            ("BOXING", "Boxing"),
                            ("CANOEING", "Canoeing"),
                            ("CYCLING", "Cycling"),
                            ("FENCING", "Fencing"),
                            ("FIGURE_SKATING", "Figure Skating"),
                            ("FOOTBALL", "Football"),
                            ("GOLF", "Golf"),
                            ("GYMNASTICS", "Gymnastics"),
                            ("HANDBALL", "Handball"),
                            ("HOCKEY", "Hockey"),
                            ("JUDO", "Judo"),
                            ("KARATE", "Karate"),
                            ("ROWING", "Rowing"),
                            ("RUGBY", "Rugby"),
                            ("SAILING", "Sailing"),
                            ("SKATING", "Skating"),
                            ("SKIING", "Skiing"),
                            ("SOFTBALL", "Softball"),
                            ("SURFING", "Surfing"),
                            ("SWIMMING", "Swimming"),
                            ("SYNCHRONIZED_SWIMMING", "Synchronized Swimming"),
                            ("TABLE_TENNIS", "Table Tennis"),
                            ("TAEKWONDO", "Taekwondo"),
                            ("TENNIS", "Tennis"),
                            ("TRIATHLON", "Triathlon"),
                            ("VOLLEYBALL", "Volleyball"),
                            ("WEIGHTLIFTING", "Weightlifting"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("PROFESSIONAL", "Professional"),
                            ("SEMI_PRO", "Semi-Pro"),
                            ("SCOUTING", "Scouting"),
                            ("COLLEGE", "College"),
                            ("UNIVERSITY_SCHOLARSHIP", "University Scholarship"),
                            ("YOUTH_CAMP", "Youth Camp"),
                            ("TRYOUT", "Tryout"),
                            ("PART_TIME", "Part Time"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MEN", "Men"), ("WOMEN", "Women"), ("COED", "Coed")],
                        max_length=10,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("link", models.URLField(max_length=500)),
                ("source", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "External Opportunity",
                "verbose_name_plural": "External Opportunities",
                "ordering": [
                    "sport",
                    "level",
                    "gender",
                    "country",
                    "deadline",
                    "title",
                ],
            },
        ),
    ]
